a ={
	"errno": 0,
	"errmsg": "",
	"consume": 138,
	"time": 1656159619,
	"data": {
		"new_anchor": {
			"list": [{
				"id": 33966013,
				"nickname": "七七ઇଓ御蒽",
				"avatar": "https://picture.s3.hualiantv.com/hualian-tupian/MzM5NjYwMTMxNjU1OTM1MjMyMDU0MTE5OTgxNDM2NDE2NTU5MzUyMTQzNTcuanBn",
				"point": 0,
				"liveid": 0
			}, {
				"id": 34119445,
				"nickname": "Dy.团子/全能",
				"avatar": "https://picture.s3.hualiantv.com/hualian-tupian/MzQxMTk0NDUxNjU1NzA0MTUwNjYzMTk4NjM3NDc0MDE2NTU3MDQxNDg5NDcuanBn",
				"point": 0,
				"liveid": 0
			}, {
				"id": 34013741,
				"nickname": "Yi.小🐟/歌",
				"avatar": "https://picture.s3.hualiantv.com/hualian-tupian/MzQwMTM3NDExNjU2MTQzOTAyOTEyMTk0MzMzNDYyNm1tZXhwb3J0MTY1NTQ4MzMwMDYxMS5qcGc=",
				"point": 0,
				"liveid": 0
			}, {
				"id": 34157306,
				"nickname": "九离ઇଓ偏爱",
				"avatar": "https://picture.s3.hualiantv.com/hualian-tupian/MzQxNTczMDYxNjU1ODc1MjkzNjQ4MTQ3MjY3MjUxODE2NTU4NzUyODI4MTUuanBn",
				"point": 0,
				"liveid": 7830
			}, {
				"id": 34142858,
				"nickname": "𝓦•洛璇",
				"avatar": "https://picture.s3.hualiantv.com/hualian-tupian/MzQxNDI4NTgxNjU1OTg4NDU5ODEyNTY2OTgwNzk3MTY1NTk4ODQ1ODA1NS5qcGc=",
				"point": 0,
				"liveid": 0
			}, {
				"id": 34136481,
				"nickname": "🌸晚瓷",
				"avatar": "https://picture.s3.hualiantv.com/hualian-tupian/MzQxMzY0ODExNjU1ODcyOTc1NDQ3MTk5NjM3MDE2ODE2NTU4NzI5NzMyNTAuanBn",
				"point": 0,
				"liveid": 7933
			}, {
				"id": 33968570,
				"nickname": "沈祈.",
				"avatar": "https://picture.s3.hualiantv.com/hualian-tupian/MzM5Njg1NzAxNjU1OTk0MTE5NDA3MjA3MjM1NTE4ODE2NTU5OTQxMTcyNjAuanBn",
				"point": 0,
				"liveid": 0
			}, {
				"id": 34091416,
				"nickname": "🍼蜜桃球球",
				"avatar": "https://picture.s3.hualiantv.com/hualian-tupian/MzQwOTE0MTYxNjU0OTQ4MjY0MzE2MTQ2NDkwMjYwNzE2NTQ5NDgyNjMwNDguanBn",
				"point": 0,
				"liveid": 0
			}, {
				"id": 34148347,
				"nickname": "Yi.喵软",
				"avatar": "https://picture.s3.hualiantv.com/hualian-tupian/MzQxNDgzNDcxNjU1Nzk5NDc0MjA0MjEyNzI0Njg4OTE2NTU3OTk0NzIxNjUuanBn",
				"point": 0,
				"liveid": 7666
			}, {
				"id": 33944798,
				"nickname": "🦄沐安安/🐑",
				"avatar": "https://picture.s3.hualiantv.com/hualian-tupian/MzM5NDQ3OTgxNjU1NTQ0NDQ4MjkwMzgxMDQ3MjQ1MTY1NTU0NDQ0NjYyNC5qcGc=",
				"point": 0,
				"liveid": 7223
			}]
		},
		"charm_anchor": {
			"list": [{
				"id": 31536579,
				"nickname": "易遥姐姐",
				"avatar": "https://picture.s3.hualiantv.com/hualian-tupian/aW1hZ2UzMTUzNjU3OTE2NTU0MDg5MzQuanBlZw==",
				"point": 0,
				"liveid": 0
			}, {
				"id": 31906032,
				"nickname": "🦢.迪士尼",
				"avatar": "https://picture.s3.hualiantv.com/hualian-tupian/aW1hZ2UzMTkwNjAzMjE2NTQ2MjA2NzAuanBlZw==",
				"point": 0,
				"liveid": 7082
			}, {
				"id": 33878542,
				"nickname": "头头儿哦",
				"avatar": "https://picture.s3.hualiantv.com/hualian-tupian/MzM4Nzg1NDIxNjQ5OTE4NTU2ODg2MTAzMDk0MjM2NGhkSW1nXzQ1OGQ0YzRiZmYzMjVhZGQ0ZWE1M2E5NzRlMjMyMjg4MTY0NTEwNDM4MjcwNy5qcGc=",
				"point": 0,
				"liveid": 7917
			}, {
				"id": 33019098,
				"nickname": "酱酱ઇଓ双修",
				"avatar": "https://picture.s3.hualiantv.com/hualian-tupian/aW1hZ2UzMzAxOTA5ODE2NTU4Mjc3NzguanBlZw==",
				"point": 0,
				"liveid": 7830
			}, {
				"id": 33401036,
				"nickname": "乖乖ઇଓ",
				"avatar": "https://picture.s3.hualiantv.com/hualian-tupian/MzM0MDEwMzYxNjU0MzI4OTE5MzY0Mzg1MDYyMTk5MTY1NDMyODkxNjk0OC5qcGc=",
				"point": 0,
				"liveid": 7830
			}, {
				"id": 33393916,
				"nickname": "卿苒/性感女神",
				"avatar": "https://picture.s3.hualiantv.com/hualian-tupian/MzMzOTM5MTYxNjU1NDQ2NjIwODMzNTQxNjMwNzUxMTY1NTQ0NjYxMTY2Ny5qcGc=",
				"point": 0,
				"liveid": 5868
			}, {
				"id": 33189719,
				"nickname": "🌈🐷爱吃粑粑",
				"avatar": "https://picture.s3.hualiantv.com/hualian-tupian/MzMxODk3MTkxNjU1OTQxODMzOTY2NTcyMzA3NDkxNjU1OTQxODI4NDM1LmpwZw==",
				"point": 0,
				"liveid": 7457
			}, {
				"id": 33650225,
				"nickname": "💭雪乐✈️",
				"avatar": "https://picture.s3.hualiantv.com/hualian-tupian/aW1hZ2UzMzY1MDIyNTE2NTU5MDUzNjkuanBlZw==",
				"point": 0,
				"liveid": 0
			}, {
				"id": 30063584,
				"nickname": "音🎵福",
				"avatar": "https://picture.s3.hualiantv.com/hualian-tupian/aW1hZ2UzMDA2MzU4NDE2NDQzNzY2NjcuanBlZw==",
				"point": 0,
				"liveid": 0
			}, {
				"id": 33843594,
				"nickname": "Yi.特蕾莎/靓",
				"avatar": "https://picture.s3.hualiantv.com/hualian-tupian/aW1hZ2UzMzg0MzU5NDE2NTYxMDIwODcuanBlZw==",
				"point": 0,
				"liveid": 7666
			}]
		}
	}
}

b = a["data"]["new_anchor"]["list"]
print(b)
for i in b:
	q = i["id"]
	print(q)
