a = {
	"errno": 0,
	"errmsg": "",
	"consume": 88,
	"time": 1653996565,
	"data": {
		"collect_list": {
			"offset": 0,
			"more": 0,
			"list": []
		},
		"room_list": {
			"offset": 40,
			"more": 1,
			"list": [{
				"prid": "365409",
				"out_id": "365409",
				"prname": "花间女友",
				"liveid": "7571",
				"cover": "https://static.s3.huajiao.com/Object.access/hj-video/NDEyYzJiYzk0YTJjY2JkOTg3MzNkNjkzNzllMmQ1NjcuanBlZw==",
				"nickname": "哥哥，恋爱选我，我超甜",
				"label_icon": "",
				"new_label_icon": "https://img.s3.hualiantv.com/hualian-houtai/MTYzNjM2NDU3Mzg4OWVhMDI4MGVlZGJmNWQ4MTFiNTU1M2E0YjVmZjBmNjcyLnBuZw==",
				"room_tag": [],
				"settle_type": "make_friends",
				"edge": "",
				"new_edge": "",
				"fever": 39743,
				"sort_fever": 39743,
				"link_num": 5,
				"is_fixed": 0,
				"fixed_position": 0,
				"is_encryption": 0,
				"room_area": 0,
				"is_banners": 0,
				"new_tags": ["1_2", "1_106", "1_8"],
				"room_pos": "C"
			}, {
				"prid": "368655",
				"out_id": "368655",
				"prname": "灯火阑珊处🧸",
				"liveid": "6861",
				"cover": "https://static.s3.huajiao.com/Object.access/hj-video/M2NjOTYxYmFkYjAyOWEzZmJkOGNjMDgyY2NkNjMyMzAuanBlZw==",
				"nickname": "我是来给我的小朋友撑腰的✨",
				"label_icon": "",
				"new_label_icon": "",
				"room_tag": ["聊天", "心动"],
				"settle_type": "new_make_friends",
				"edge": "",
				"new_edge": "",
				"fever": 22926,
				"sort_fever": 22926,
				"link_num": 8,
				"is_fixed": 0,
				"fixed_position": 0,
				"is_encryption": 0,
				"room_area": 0,
				"is_banners": 0,
				"new_tags": ["1_2", "1_27"],
				"room_pos": "C"
			}, {
				"prid": "368596",
				"out_id": "368596",
				"prname": "西雅图",
				"liveid": "7547",
				"cover": "https://static.s3.huajiao.com/Object.access/hj-video/ZDE0NDgyNGQxMDE1ZmY3M2U5N2ZjMWE0MDUzNGU3NmEuanBlZw==",
				"nickname": "西雅图招女婿",
				"label_icon": "",
				"new_label_icon": "",
				"room_tag": ["红颜"],
				"settle_type": "make_friends",
				"edge": "",
				"new_edge": "",
				"fever": 21894,
				"sort_fever": 21894,
				"link_num": 9,
				"is_fixed": 0,
				"fixed_position": 0,
				"is_encryption": 0,
				"room_area": 0,
				"is_banners": 0,
				"new_tags": ["1_2", "1_8"],
				"room_pos": "C"
			}, {
				"prid": "363713",
				"out_id": "363713",
				"prname": "恋爱日记",
				"liveid": "6502",
				"cover": "https://picture.s3.hualiantv.com/hualian-tupian/MzM3MTIwMzcxNjUzMTE5MTcyNDk4MTc2NjA2MDQzMDE2NTMxMTkxNzA5ODAuanBn",
				"nickname": "你的专属女友🍓",
				"label_icon": "",
				"new_label_icon": "",
				"room_tag": ["红颜", "女友"],
				"settle_type": "make_friends",
				"edge": "",
				"new_edge": "",
				"fever": 12433,
				"sort_fever": 12433,
				"link_num": 9,
				"is_fixed": 0,
				"fixed_position": 0,
				"is_encryption": 0,
				"room_area": 0,
				"is_banners": 0,
				"new_tags": ["1_2", "1_8"],
				"room_pos": "C"
			}, {
				"prid": "367836",
				"out_id": "367836",
				"prname": "诱御恋人",
				"liveid": "7587",
				"cover": "https://static.s3.huajiao.com/Object.access/hj-video/MzU3NDFjNjVjNjQ0MzI3OTllOTkxOWY4Y2M1MjQyYzUuanBlZw==",
				"nickname": "  新厅开业☞求冠名",
				"label_icon": "",
				"new_label_icon": "https://img.s3.hualiantv.com/hualian-houtai/MTYzNjM2NDU3Mzg4OWVhMDI4MGVlZGJmNWQ4MTFiNTU1M2E0YjVmZjBmNjcyLnBuZw==",
				"room_tag": [],
				"settle_type": "make_friends",
				"edge": "",
				"new_edge": "",
				"fever": 29861,
				"sort_fever": 29861,
				"link_num": 4,
				"is_fixed": 0,
				"fixed_position": 0,
				"is_encryption": 0,
				"room_area": 0,
				"is_banners": 0,
				"new_tags": ["1_2", "1_8", "1_106"],
				"room_pos": "C"
			}, {
				"prid": "362752",
				"out_id": "362752",
				"prname": "欲望酒馆",
				"liveid": "6806",
				"cover": "https://static.s3.huajiao.com/Object.access/hj-video/OGY4ZDIzY2M5YjhmYmU4ZTdlOWQ5N2Q3MGEzYzBlMDIuanBlZw==",
				"nickname": "烈酒与你",
				"label_icon": "",
				"new_label_icon": "",
				"room_tag": ["红颜", "女友"],
				"settle_type": "make_friends",
				"edge": "",
				"new_edge": "",
				"fever": 12039,
				"sort_fever": 12039,
				"link_num": 9,
				"is_fixed": 0,
				"fixed_position": 0,
				"is_encryption": 0,
				"room_area": 0,
				"is_banners": 0,
				"new_tags": ["1_2", "1_8"],
				"room_pos": "C"
			}, {
				"prid": "363476",
				"out_id": "363476",
				"prname": "华灯初上🌇",
				"liveid": "6778",
				"cover": "https://picture.s3.hualiantv.com/hualian-tupian/MzIyOTcxNTIxNjUzMTAyOTg5NjM4MTY5NTgwODMxNzE2NTMxMDI5ODY4NjIuanBn",
				"nickname": "✨六一限定小可爱已上线✨",
				"label_icon": "",
				"new_label_icon": "",
				"room_tag": ["心动", "聊天"],
				"settle_type": "new_make_friends",
				"edge": "",
				"new_edge": "",
				"fever": 9901,
				"sort_fever": 9901,
				"link_num": 9,
				"is_fixed": 0,
				"fixed_position": 0,
				"is_encryption": 0,
				"room_area": 0,
				"is_banners": 0,
				"new_tags": ["1_2", "1_27"],
				"room_pos": "C"
			}, {
				"prid": "369575",
				"out_id": "369575",
				"prname": "💞酥魅女神🔥",
				"liveid": "5940",
				"cover": "https://picture.s3.hualiantv.com/hualian-tupian/MzMzNjk5MjcxNjUzMTE3Njk3NTIxNjE2MDczMzI2bW1leHBvcnQxNjUzMTE3Njg5MjA0LmpwZw==",
				"nickname": "一遇柚子误终生❤️",
				"label_icon": "",
				"new_label_icon": "",
				"room_tag": ["红颜", "女友"],
				"settle_type": "make_friends",
				"edge": "",
				"new_edge": "",
				"fever": 8782,
				"sort_fever": 8782,
				"link_num": 9,
				"is_fixed": 0,
				"fixed_position": 0,
				"is_encryption": 0,
				"room_area": 0,
				"is_banners": 0,
				"new_tags": ["1_2", "1_8"],
				"room_pos": "C"
			}, {
				"prid": "363488",
				"out_id": "363488",
				"prname": "心动男友",
				"liveid": "7610",
				"cover": "https://static.s3.huajiao.com/Object.access/hj-video/NWM5NjFhMDA0ZjNlM2Y0NTZkZjc1ZDQwOWE5MWNhNzIuanBlZw==",
				"nickname": "新厅开业",
				"label_icon": "",
				"new_label_icon": "https://img.s3.hualiantv.com/hualian-houtai/MTYzNjM2NDU3Mzg4OWVhMDI4MGVlZGJmNWQ4MTFiNTU1M2E0YjVmZjBmNjcyLnBuZw==",
				"room_tag": [],
				"settle_type": "make_friends",
				"edge": "",
				"new_edge": "",
				"fever": 10779,
				"sort_fever": 10779,
				"link_num": 3,
				"is_fixed": 0,
				"fixed_position": 0,
				"is_encryption": 0,
				"room_area": 0,
				"is_banners": 0,
				"new_tags": ["1_2", "1_106", "1_13"],
				"room_pos": "C"
			}, {
				"prid": "364262",
				"out_id": "366888",
				"prname": "一语定情🌷",
				"liveid": "5966",
				"cover": "https://picture.s3.hualiantv.com/hualian-tupian/aW1hZ2UzMTQ1NDcxMzE2NTM5NjQyMzIuanBlZw==",
				"nickname": "ʚ🐰ɞ这个六一忙着可爱了-",
				"label_icon": "",
				"new_label_icon": "",
				"room_tag": ["才艺", "女友"],
				"settle_type": "new_make_friends",
				"edge": "",
				"new_edge": "",
				"fever": 8764,
				"sort_fever": 8764,
				"link_num": 8,
				"is_fixed": 0,
				"fixed_position": 0,
				"is_encryption": 0,
				"room_area": 0,
				"is_banners": 0,
				"new_tags": ["1_2", "1_8"],
				"room_pos": "C"
			}, {
				"prid": "367895",
				"out_id": "367895",
				"prname": "一见钟情",
				"liveid": "7305",
				"cover": "https://picture.s3.hualiantv.com/hualian-tupian/MzIyNTExMjExNjUzMTA5MjE5NjA3MTM2NzY0ODEwMDE2NTMxMDkyMTgwMTYuanBn",
				"nickname": "做你的心上女神",
				"label_icon": "",
				"new_label_icon": "",
				"room_tag": ["聊天", "心动"],
				"settle_type": "new_make_friends",
				"edge": "",
				"new_edge": "",
				"fever": 8648,
				"sort_fever": 8648,
				"link_num": 8,
				"is_fixed": 0,
				"fixed_position": 0,
				"is_encryption": 0,
				"room_area": 0,
				"is_banners": 0,
				"new_tags": ["1_2", "1_27"],
				"room_pos": "C"
			}, {
				"prid": "367077",
				"out_id": "367077",
				"prname": "Mt宝格丽之臻哥冠",
				"liveid": "6728",
				"cover": "https://picture.s3.hualiantv.com/hualian-tupian/aW1hZ2UzMzI2NjY0NTE2NTMxMzU3NTUuanBlZw==",
				"nickname": "💕为你而来，为爱而冠💕",
				"label_icon": "",
				"new_label_icon": "",
				"room_tag": ["心动", "聊天"],
				"settle_type": "make_friends",
				"edge": "",
				"new_edge": "",
				"fever": 8631,
				"sort_fever": 8631,
				"link_num": 9,
				"is_fixed": 0,
				"fixed_position": 0,
				"is_encryption": 0,
				"room_area": 0,
				"is_banners": 0,
				"new_tags": ["1_2", "1_27"],
				"room_pos": "C"
			}, {
				"prid": "360736",
				"out_id": "363555",
				"prname": "百花楼",
				"liveid": "6570",
				"cover": "https://picture.s3.hualiantv.com/hualian-tupian/MzIzNzc3MTAxNjUzMTQ4MTkwNDAyNjgzNTkzNTUyMTY1MzE0ODE4ODczMS5qcGc=",
				"nickname": "花有重开日，人无再少年！",
				"label_icon": "",
				"new_label_icon": "",
				"room_tag": ["才艺", "开黑"],
				"settle_type": "make_friends",
				"edge": "",
				"new_edge": "",
				"fever": 137027,
				"sort_fever": 137027,
				"link_num": 7,
				"is_fixed": 0,
				"fixed_position": 0,
				"is_encryption": 0,
				"room_area": 0,
				"is_banners": 0,
				"new_tags": ["1_8", "1_2"],
				"room_pos": "C"
			}, {
				"prid": "365087",
				"out_id": "365087",
				"prname": "Ms.慕斯男神",
				"liveid": "6831",
				"cover": "https://static.s3.huajiao.com/Object.access/hj-video/MTlhYjg0NjdiZTcyYWRhZTI4NDk2MGZhMWU4N2NjNGYuanBlZw==",
				"nickname": "谢谢你，一路陪我到这里",
				"label_icon": "",
				"new_label_icon": "",
				"room_tag": ["蓝颜"],
				"settle_type": "make_friends",
				"edge": "",
				"new_edge": "",
				"fever": 8395,
				"sort_fever": 8395,
				"link_num": 8,
				"is_fixed": 0,
				"fixed_position": 0,
				"is_encryption": 0,
				"room_area": 0,
				"is_banners": 0,
				"new_tags": ["1_2", "1_13"],
				"room_pos": "C"
			}, {
				"prid": "360106",
				"out_id": "360106",
				"prname": "甜酒少女🍸新厅开业",
				"liveid": "7500",
				"cover": "https://static.s3.huajiao.com/Object.access/hj-video/ZDY4OWM2ZmM1ZDg5Y2E5ZTQ2ODdiZTg2M2U3Y2VlZWQuanBlZw==",
				"nickname": "酒不醉人 美人醉，全麦单身可萝可御",
				"label_icon": "",
				"new_label_icon": "https://img.s3.hualiantv.com/hualian-houtai/MTYzNjM2NDU3Mzg4OWVhMDI4MGVlZGJmNWQ4MTFiNTU1M2E0YjVmZjBmNjcyLnBuZw==",
				"room_tag": ["红颜", "女友"],
				"settle_type": "make_friends",
				"edge": "",
				"new_edge": "",
				"fever": 5018,
				"sort_fever": 5018,
				"link_num": 4,
				"is_fixed": 0,
				"fixed_position": 0,
				"is_encryption": 0,
				"room_area": 0,
				"is_banners": 0,
				"new_tags": ["1_2", "1_8", "1_106"],
				"room_pos": "C"
			}, {
				"prid": "368070",
				"out_id": "368070",
				"prname": "月落银河",
				"liveid": "6956",
				"cover": "https://static.s3.huajiao.com/Object.access/hj-video/MzBhZjVjZjI0NzRkY2Q0MTlkNWU2YTRmODFlYWUzOWYuanBlZw==",
				"nickname": "全麦初恋",
				"label_icon": "",
				"new_label_icon": "",
				"room_tag": [],
				"settle_type": "make_friends",
				"edge": "",
				"new_edge": "",
				"fever": 4163,
				"sort_fever": 4163,
				"link_num": 8,
				"is_fixed": 0,
				"fixed_position": 0,
				"is_encryption": 0,
				"room_area": 0,
				"is_banners": 0,
				"new_tags": ["1_2", "1_8"],
				"room_pos": "C"
			}, {
				"prid": "363696",
				"out_id": "363696",
				"prname": "可乐加宾",
				"liveid": "7328",
				"cover": "https://static.s3.huajiao.com/Object.access/hj-video/NjVhMTUzOTExY2NlNjUxMjhiNzMwMWMxMTAwOGMyYTkuanBlZw==",
				"nickname": "可乐加宾 如乐所致",
				"label_icon": "",
				"new_label_icon": "",
				"room_tag": [],
				"settle_type": "make_friends",
				"edge": "",
				"new_edge": "",
				"fever": 38891,
				"sort_fever": 38891,
				"link_num": 7,
				"is_fixed": 0,
				"fixed_position": 0,
				"is_encryption": 0,
				"room_area": 0,
				"is_banners": 0,
				"new_tags": ["1_2", "1_8", "1_27"],
				"room_pos": "C"
			}, {
				"prid": "364147",
				"out_id": "364147",
				"prname": "甜心女友✨",
				"liveid": "7502",
				"cover": "https://static.s3.huajiao.com/Object.access/hj-video/MzAxMDg1MjNjNDQwNTI1MzE0M2QyYmY3NzFkY2ZjYmIuanBlZw==",
				"nickname": "甜心女友甜心未泯🎉",
				"label_icon": "",
				"new_label_icon": "",
				"room_tag": [],
				"settle_type": "new_make_friends",
				"edge": "",
				"new_edge": "",
				"fever": 33000,
				"sort_fever": 33000,
				"link_num": 7,
				"is_fixed": 0,
				"fixed_position": 0,
				"is_encryption": 0,
				"room_area": 0,
				"is_banners": 0,
				"new_tags": ["1_2", "1_8"],
				"room_pos": "C"
			}, {
				"prid": "361691",
				"out_id": "361691",
				"prname": "三月酒馆",
				"liveid": "7293",
				"cover": "https://static.s3.huajiao.com/Object.access/hj-video/NTI4MGZlZTQ0OGE2ZDg3MDEzMmQ1MjU5ZWFjZmVjN2EuZ2lm",
				"nickname": "等一个不问归期的你",
				"label_icon": "",
				"new_label_icon": "https://static.s3.huajiao.com/Object.access/hj-video/YTU1YTdmYWZhNTI0NDk2ZDhmZDBlMWZiNmYzMWVkMDMucG5n",
				"room_tag": [],
				"settle_type": "make_friends",
				"edge": "",
				"new_edge": "",
				"fever": 32396,
				"sort_fever": 32396,
				"link_num": 7,
				"is_fixed": 0,
				"fixed_position": 0,
				"is_encryption": 0,
				"room_area": 0,
				"is_banners": 0,
				"new_tags": ["1_2", "1_8"],
				"room_pos": "C"
			}, {
				"prid": "361130",
				"out_id": "361130",
				"prname": "布拉格",
				"liveid": "7496",
				"cover": "https://static.s3.huajiao.com/Object.access/hj-video/OGNlOTQ5ZTU4MDlhOGI0OTU0MWZmNDQ5NmI5ZjI1NzUuanBlZw==",
				"nickname": "布拉格新厅开业",
				"label_icon": "",
				"new_label_icon": "https://img.s3.hualiantv.com/hualian-houtai/MTYzNjM2NDU3Mzg4OWVhMDI4MGVlZGJmNWQ4MTFiNTU1M2E0YjVmZjBmNjcyLnBuZw==",
				"room_tag": [],
				"settle_type": "make_friends",
				"edge": "",
				"new_edge": "",
				"fever": 5005,
				"sort_fever": 5005,
				"link_num": 3,
				"is_fixed": 0,
				"fixed_position": 0,
				"is_encryption": 0,
				"room_area": 0,
				"is_banners": 0,
				"new_tags": ["1_2", "1_8", "1_106"],
				"room_pos": "C"
			}]
		}
	}
}

b = a["data"]["room_list"]["list"]
for i in b:
    o = i["sort_fever"]
print(o)